version: "3.9"

services:
  icarus:
    image: postgres:13
    restart: always
    ports:
      - "9999:5432"
    environment:
      POSTGRES_DB: icarus
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data